### PR TITLE
forgot the filename

### PR DESCRIPTION
**Pull request by ghost**
guess there are still some missing lines on en_US.
could you please add them?

### CODE REVIEW

**Comment by ghost** [comment]
lol i forgot to add the filename extension.

**Comment by Shadows-of-Fire** [comment]
I've added two more lang keys as of 8b6e81f.  Going to close this since the file extension is missing anyway, which would be invalid.  The structure names on the tooltip cannot be translated, as the game cannot recognize them unless they are in English due to requiring use of `/locate` internally.

**Comment by Shadows-of-Fire** [comment]
I'll be working on adding additional lang keys if you want to postpone translation further.

**Comment by Shadows-of-Fire** [comment]
Proper localization support and appropriate lang keys have been added as of 985b602 (CF Release 3.3.0)

**Comment by ghost** [comment]
yeah, i'll be looking forward to it

**Pull request closed without merging**
